
export enum JobErrorCode {
  INVALID_JOB_DATA = 'INVALID_JOB_DATA',
  JOB_CREATION_FAILED = 'JOB_CREATION_FAILED',
  JOB_NOT_FOUND = 'JOB_NOT_FOUND',
  JOB_EXECUTION_FAILED = 'JOB_EXECUTION_FAILED',
  AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
  AUTHORIZATION_FAILED = 'AUTHORIZATION_FAILED',
  NETWORK_ERROR = 'NETWORK_ERROR',
  TIMEOUT = 'TIMEOUT',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
}
